Removed redundant code, added ESLint and reformatted whole project
Cheeth4/vue-app pull request #4
Opened 2022-08-24 19:57 UTC by Cheeth4

2022-08-25 13:08 UTC, szymonlicau requested changes

2022-08-25 13:08 UTC, szymonlicau commented on src/components/app/movies/MovieCardTemplate.vue
> +import UseMovie from '@/compositions/components/UseMovie.vue';
`UseMovie` is definitely a bit odd component name.
What is the purpose of such component? If it's to display the details of a movie then perhaps... `MovieDetails`? 🤔
Or is it something else?

2022-08-25 13:08 UTC, szymonlicau commented on src/components/app/movies/MovieCard.vue
> +        alt="terminator"
Would it *always* be terminator or should it be more relevant to the actual movie passed as a prop? 😄

2022-08-25 13:08 UTC, szymonlicau commented on src/components/app/forms/FormLogin.vue
> +};
Why not write this in `async/await` syntax? 🤔

2022-08-25 13:08 UTC, szymonlicau commented on src/app/screenings/Screenings.vue
> +import ScreeningsList from '@components/screenings/ScreeningsList.vue';</script>
```suggestion
import ScreeningsList from '@components/screenings/ScreeningsList.vue';
</script>
```

2022-08-25 13:08 UTC, szymonlicau commented on src/app/landing/Landing.vue
>      <MonteBreadcrumb style="margin-bottom: 64px" />
Avoid using inline styles 😄
If you need the margin - define a class in `<style>` and apply it here.

2022-08-25 13:46 UTC, Cheeth4 commented on src/i18n/locales/index.ts
> +import pl from './_pl';
So that the `index.ts` will always appear at the very bottom in my code editor.

2022-08-25 14:14 UTC, Cheeth4 commented on src/router/index.ts
> +    await openLoginModal({ from, redirect: to });
It opens a login modal if the user wants to access a protected route (booking for example):
- rejects the navigation if no action is taken,
- redirects to the target route if the user logs in,
- allows to navigate to the register page with preserved redirect query, so after the registration the user will be redirected to the proper route.

Actually, we *do have* it - "Design system" page on Figma. I understand it wasn't a "must have", kinda implemented it for fun.

2022-08-25 14:20 UTC, szymonlicau commented on src/router/index.ts
> +    await openLoginModal({ from, redirect: to });
We should stick to the design provided and implement it as is - in a real project we want to implement the UX that is agreed upon so in your free time I'd suggest to change it. Otherwise, it can stay for now.
On the Design system page what we do have is just details about the form, nothing suggests it's a modal on all the pages provided in the Montecinema page.
If you are not sure though - you *definitely* should ask and confirm your assumptions before implementing too 💡

2022-08-25 14:21 UTC, szymonlicau commented on src/i18n/locales/index.ts
> +import pl from './_pl';
That is... not a very strong upside to this decision. I'd recommend to stick to normal file names in the future

2022-08-25 14:34 UTC, Cheeth4 commented on src/components/ui/table/MonteTable.vue
> +import { ElTable } from 'element-plus';
Yeah and I already encountered issues, because it's impossible to make it fully responsive. I will code my own solution later.

2022-08-25 14:39 UTC, szymonlicau commented on src/components/ui/table/MonteTable.vue
> +import { ElTable } from 'element-plus';
I think this is a good lesson to start simple and only introduce complexity if it's necessary 😃
A custom solution wouldn't take a lot of time and can be easily tweaked

2022-08-25 14:51 UTC, Cheeth4 commented on src/components/app/movies/MovieCardTemplate.vue
> +import UseMovie from '@/compositions/components/UseMovie.vue';
It's a renderless component. I pass some common movie logic to the component's slot (production year and formatted length) and then reuse it where I need it. https://github.com/Cheeth4/vue-app/blob/main/src/compositions/components/UseMovie.vue

Maybe the name is weird, but that's my naming convention for such components, same as for normal compositions - UseSomething.

2022-08-25 14:53 UTC, Cheeth4 commented on src/app/screenings/Screenings.vue
> +import ScreeningsList from '@components/screenings/ScreeningsList.vue';</script>
Yeah, I don't know how to disable such behavior in WebStorm when formatting a file. I will look for a solution later.

2022-08-25 14:57 UTC, Cheeth4 commented on src/components/app/forms/FormLogin.vue
> +};
Okay, I will change it.

2022-08-25 14:57 UTC, szymonlicau commented on src/components/app/movies/MovieCardTemplate.vue
> +import UseMovie from '@/compositions/components/UseMovie.vue';
Sounds like it's an overcomplicated composable then 😅

2022-08-25 15:23 UTC, Cheeth4 commented on src/components/app/movies/MovieCardTemplate.vue
> +import UseMovie from '@/compositions/components/UseMovie.vue';
I think it was a good solution when there was only OptionsAPI. Now we can just make a composable, which would take a movie object as a parameter and have the same benefit + be able to use its logic also inside <script>.

2022-08-29 07:56 UTC, szymonlicau requested changes

2022-08-29 07:56 UTC, szymonlicau commented on .eslintrc.cjs
> +    "@typescript-eslint/no-unused-vars": 1  }
What were your issues with the `no-unused-vars` rules? 🤔

2022-08-29 07:56 UTC, szymonlicau commented on src/app/contact/Contact.vue
>          Poland
You could also put all of these in your locales and use i18n for them, even though they wouldn't change between english/polish/etc.
Why?
If we define our i18n properly and have a fallback locale, it's a great source for having all of our body copy mapped out.

2022-08-29 07:56 UTC, szymonlicau commented on src/app/landing/Landing.vue
> +  >
While this works and is mostly okay I'd suggest to introduce `meta` fields on your routes in the future and use these in your conditionals 💡
Feel free to leave it for now.

2022-08-29 07:56 UTC, szymonlicau commented on src/components/ui/table/index.ts
> +};
Again, please don't use files like these 😃

2022-08-29 07:56 UTC, szymonlicau commented on src/app/booking/summary/BookingSummary.vue
> +const { formatDatetime } = useFormatters();
Wouldn't it make more sense to have them as simple utility functions?

2022-08-29 07:56 UTC, szymonlicau commented on src/components/ui/table/MonteTable.vue
> +              </slot>
I kind of still honestly get the reason for this table component.
It's overly complicated and way too generic to be used easily, has dynamic slot names and none of the designs suggest creating such a component - do we have any tables that would warrant this? I'd argue to say no - everything could be solved by simple components and flex/grid usage.

It's overengineering at best and it makes your code a bit harder to parse and understand.
If you really want to use it then be free to do so, but keep in mind that I do not see much value in this at all so far.

2022-08-29 07:57 UTC, szymonlicau commented on src/components/app/movies/MovieCardTemplate.vue
> +import UseMovie from '@/compositions/components/UseMovie.vue';
Still, we have composition API now, no need for overcomplicating our templates 😄

2022-08-29 09:38 UTC, Cheeth4 commented on .eslintrc.cjs
> +    "@typescript-eslint/no-unused-vars": 1  }
When declaring a type of a function (in defineEmits) the linter would always yell about unused parameters.

2022-08-29 09:43 UTC, Cheeth4 commented on src/app/landing/Landing.vue
> +  >
I will do it better, but later.

2022-08-29 09:44 UTC, Cheeth4 commented on src/components/ui/table/index.ts
> +};
I know, I will get rid of these files in the next refactor.

2022-08-29 09:53 UTC, Cheeth4 commented on src/components/ui/table/MonteTable.vue
> +              </slot>
I know it's overengineering, but at that time I had no other idea. I will think about better solution, maybe I won't even use tables at all. For now it works as expected.

2022-08-29 09:53 UTC, szymonlicau commented on .eslintrc.cjs
> +    "@typescript-eslint/no-unused-vars": 1  }
It shouldn't if you have defined it properly.
Do you have any examples?

2022-08-29 09:54 UTC, szymonlicau commented on src/components/ui/table/MonteTable.vue
> +              </slot>
If you know it - act upon it 😉

2022-08-29 10:16 UTC, Cheeth4 commented on .eslintrc.cjs
> +    "@typescript-eslint/no-unused-vars": 1  }
Okay, now I see it works without any "tricks" and I pushed the fixed eslint config.

2022-08-29 10:55 UTC, Cheeth4 commented on src/app/booking/summary/BookingSummary.vue
> +const { formatDatetime } = useFormatters();
For now I will leave it as it is. Later I will make an `utils` directory and put all similar logic there.

2022-08-29 11:14 UTC, szymonlicau approved these changes
There is *a lot* of things you want/plan to do in the future/next PRs so I hope you can keep track of that and also realized the importance of early and consistent code review 🙏

2022-08-29 12:31 UTC, merged